// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyIO7RoxgnqHRt0YtADaw335SqDUgRtA',
    appId: '1:494259036461:android:98da918ca4034b7dd3f3a4',
    messagingSenderId: '494259036461',
    projectId: 'sample-app-14c2f',
    storageBucket: 'sample-app-14c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbT687EPyckLXUQsg2FKIqNiVMXOCSAuA',
    appId: '1:494259036461:ios:7e5d64cfb3135130d3f3a4',
    messagingSenderId: '494259036461',
    projectId: 'sample-app-14c2f',
    storageBucket: 'sample-app-14c2f.appspot.com',
    androidClientId: '494259036461-80c9emkpudqgciuvbmg28tetsflgb1oc.apps.googleusercontent.com',
    iosClientId: '494259036461-3paaal92bv22frk3b5mp95bf6ndhd3vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
